version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "yaml2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6uldy9atsjja"
s3_prefix = "yaml2"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
