AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A sample yaml template to create a table in DynamoDB
Resources:
  LambdaCreateTable:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs14.x
      Timeout: 3
      Environment:
        Variables:
          DatabaseTable: !Ref DynamoTable
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  LambdaFunction:
    Value: !Ref LambdaCreateTable
    Description: A function to create table

  DynamoDbTable:
    Value: !Ref DynamoTable
    Description: Dynamo Table
