AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: A sample yaml template to write into DynamoDB
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs14.x
      Timeout: 3

Outputs:
  LambdaFunctionName:
    Description: A Lambda Function
    Value: !Ref LambdaFunction
