version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "newYaml"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rgcd7nhtj5ot"
s3_prefix = "newYaml"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
